"""ELiXX Studio (Fase 25) — ambiente visual de desenvolvimento.

Fundação: projeto, workspace, documentos, editor, preview (Tk e
headless), inspetor, assets, timeline, logs, diagnósticos, comandos,
eventos e configuração — sobre o MESMO modelo semântico do
compilador/runtime (nunca um "mini-ELiXX" paralelo).

"O Studio é uma ferramenta de desenvolvimento do ELiXX, não uma
dependência necessária para executar aplicações ELiXX."

"Código e visual são representações diferentes do mesmo projeto."
"""
from elixx.studio.app import StudioApp
from elixx.studio.arquivos import ArvoreArquivos
from elixx.studio.assets import Asset, GerenciadorAssets
from elixx.studio.cena import ModeloCena, Timeline, timeline_de_motions
from elixx.studio.comandos import (
    AgentChange,
    AgentCommand,
    AgentContext,
    AgentProposal,
    FilaComandos,
    StudioCommand,
)
from elixx.studio.documento import DocumentoELiXX, GerenciadorDocumentos
from elixx.studio.editor import (
    Diagnostic,
    EditorCodigo,
    diagnosticar_texto,
)
from elixx.studio.estado import Configuracao
from elixx.studio.eventos import EventBus
from elixx.studio.inspetor import (
    InspecaoPersonagem,
    Inspetor,
    Selecao,
    fluxo_personagem,
)
from elixx.studio.logs import PainelLogs
from elixx.studio.preview import (
    HeadlessPreview,
    PreviewResultado,
    StudioPreview,
    TkPreview,
)
from elixx.studio.projeto import ProjetoELiXX
from elixx.studio.workspace import Workspace
from elixx.studio.ux import (
    AbasEditor,
    SecaoInspector,
    ZOOM_NIVEIS,
    cabecalho_arquivo,
    destacar_semantico,
    formatar_arvore,
    resumo_agente,
)
from elixx.studio.tema import (
    ELIXX_BORDERS,
    ELIXX_COLORS,
    ELIXX_DENSITY,
    ELIXX_FONTS,
    ELIXX_METRICS,
    ELIXX_RADIUS,
    ELIXX_SPACING,
    ELIXX_DS3,
    ELIXX_TYPE,
    ELIXX_SPACE,
    ELIXX_RADIUS_V3,
    aplicar_tema,
    paleta,
    estilizar_tk,
    titulo_escuro,
    validar_ds3,
    contraste,
    validar_tokens,
)
from elixx.studio.scene_editor import (
    ABAS_FUNDO,
    ABA_PARA_PAINEL,
    ATALHOS_F39,
    COMANDOS_F39,
    GIZMOS,
    ITENS_TOOLBAR,
    MODOS_F39,
    MODOS_WORKSPACE,
    PAINEIS_POR_MODO,
    RESOLUCOES_QA,
    SNAPS_F39,
    ZOOM_F39,
    BottomWorkspace,
    BoundingBox,
    GizmoStatus,
    SceneEditor,
    SceneToolbar,
    StatusBar,
    WorkspaceModes,
    buscar_palette_f39,
    conflitos_f39,
    entidade_do_cursor,
    erro_amigavel,
    executar_palette_f39,
    gizmo_para_modo,
    gizmo_status,
    ir_para_codigo,
    montar_status,
)
from elixx.studio.scene_canvas import (
    ATALHOS_F40,
    COMANDOS_F40,
    KINDS,
    PLACEHOLDER_KINDS,
    PROPORCOES_SCENE,
    TAMANHOS_PADRAO,
    AnimationPreview,
    MotionPreview,
    RenderObject,
    SceneCanvas,
    abrir_janela_cena,
    aplicar_compacto,
    aplicar_edicao,
    aplicar_layout_scene,
    buscar_palette_f40,
    carregar_imagem,
    cena_de_texto,
    conflitos_f40,
    contexto_cena,
    desenhar,
    estado_asset,
    executar_palette_f40,
    ficha_objeto,
    proporcoes_scene,
)
from elixx.studio.projeto_workspace import (
    ATALHOS_F41,
    COMANDOS_F41,
    CONFLITOS_F41,
    TEMPLATES,
    TIPOS_ARQUIVO,
    AbasAvancadas,
    ArvoreProjetoReal,
    BoasVindas,
    EstadoExecucao,
    EstadoProjeto,
    Fotografia,
    Recentes,
    abrir_projeto_validado,
    buscar_palette_f41,
    conflitos_f41,
    conteudo_inicial,
    conteudo_template,
    descartar_alteracoes,
    duplicar_arquivo,
    estado_arquivo,
    estado_projeto,
    executar_palette_f41,
    executar_projeto,
    fechar_projeto,
    interpretar_arrastar,
    menu_contexto,
    novo_projeto,
    parar_execucao,
    recarregar_projeto,
)
from elixx.studio.workspace_ui import (
    ArvoreProjeto,
    ConsoleModelo,
    DiagnosticosModelo,
    EditorModelo,
    InspectorModelo,
    Layout,
    PainelAgent,
    PreviewModelo,
    StudioWorkspace,
    destacar_lexico,
    estado_vazio,
    montar_workspace_ui,
    resumo_status,
)

__all__ = [
    "StudioApp",
    "ArvoreArquivos",
    "Asset", "GerenciadorAssets",
    "ModeloCena", "Timeline", "timeline_de_motions",
    "AgentChange", "AgentCommand", "AgentContext", "AgentProposal",
    "FilaComandos", "StudioCommand",
    "DocumentoELiXX", "GerenciadorDocumentos",
    "Diagnostic", "EditorCodigo", "diagnosticar_texto",
    "Configuracao",
    "EventBus",
    "InspecaoPersonagem", "Inspetor", "Selecao", "fluxo_personagem",
    "PainelLogs",
    "HeadlessPreview", "PreviewResultado", "StudioPreview",
    "TkPreview",
    "ProjetoELiXX",
    "Workspace",
    "ArvoreProjeto", "ConsoleModelo", "DiagnosticosModelo",
    "EditorModelo", "InspectorModelo", "Layout", "PainelAgent",
    "PreviewModelo", "StudioWorkspace", "destacar_lexico",
    "estado_vazio", "montar_workspace_ui", "resumo_status",
    "ELIXX_BORDERS", "ELIXX_COLORS", "ELIXX_DENSITY",
    "ELIXX_FONTS", "ELIXX_METRICS", "ELIXX_RADIUS",
    "ELIXX_SPACING", "ELIXX_DS3", "ELIXX_TYPE",
    "ELIXX_SPACE", "ELIXX_RADIUS_V3",
    "aplicar_tema", "paleta", "estilizar_tk",
    "titulo_escuro", "validar_ds3", "contraste",
    "validar_tokens",
    "AbasEditor", "SecaoInspector", "ZOOM_NIVEIS",
    "cabecalho_arquivo", "destacar_semantico",
    "formatar_arvore", "resumo_agente",
    "ABAS_FUNDO", "ABA_PARA_PAINEL", "ATALHOS_F39",
    "COMANDOS_F39", "GIZMOS", "ITENS_TOOLBAR",
    "MODOS_F39", "MODOS_WORKSPACE", "PAINEIS_POR_MODO",
    "RESOLUCOES_QA", "SNAPS_F39", "ZOOM_F39",
    "BottomWorkspace", "BoundingBox", "GizmoStatus",
    "SceneEditor", "SceneToolbar", "StatusBar",
    "WorkspaceModes", "buscar_palette_f39", "conflitos_f39",
    "entidade_do_cursor", "erro_amigavel",
    "executar_palette_f39", "gizmo_para_modo", "gizmo_status",
    "ir_para_codigo", "montar_status",
    "ATALHOS_F40", "COMANDOS_F40", "KINDS",
    "PLACEHOLDER_KINDS", "PROPORCOES_SCENE", "TAMANHOS_PADRAO",
    "AnimationPreview", "MotionPreview", "RenderObject",
    "SceneCanvas", "abrir_janela_cena", "aplicar_compacto",
    "aplicar_edicao", "aplicar_layout_scene",
    "buscar_palette_f40", "carregar_imagem", "cena_de_texto",
    "conflitos_f40", "contexto_cena", "desenhar",
    "estado_asset", "executar_palette_f40", "ficha_objeto",
    "proporcoes_scene",
    "ATALHOS_F41", "COMANDOS_F41",
    "CONFLITOS_F41", "TEMPLATES", "TIPOS_ARQUIVO",
    "AbasAvancadas", "ArvoreProjetoReal", "BoasVindas",
    "EstadoExecucao", "EstadoProjeto", "Fotografia",
    "Recentes",
    "abrir_projeto_validado", "buscar_palette_f41",
    "conflitos_f41", "conteudo_inicial", "conteudo_template",
    "descartar_alteracoes", "duplicar_arquivo",
    "estado_arquivo", "estado_projeto", "executar_palette_f41",
    "executar_projeto", "fechar_projeto", "interpretar_arrastar",
    "menu_contexto", "novo_projeto", "parar_execucao",
    "recarregar_projeto",
]
